services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME:-payment_db}
      - DB_SSLMODE=disable
      - PORT=8082
      - MERCADO_PAGO_BASEURL=${MERCADO_PAGO_BASEURL}
      - MERCADO_PAGO_ACCESS_TOKEN=${MERCADO_PAGO_ACCESS_TOKEN}
      - MERCADO_PAGO_CLIENT_ID=${MERCADO_PAGO_CLIENT_ID}
      - MERCADO_PAGO_POS_ID=${MERCADO_PAGO_POS_ID}
      - MERCADO_PAGO_WEBHOOK_SECRET=${MERCADO_PAGO_WEBHOOK_SECRET}
      - MERCADO_PAGO_WEBHOOK_CALLBACK_URL=${MERCADO_PAGO_WEBHOOK_CALLBACK_URL}
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:15
    container_name: payment_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME:-payment_db}
    ports:
      - "5434:5432"
    volumes:
      - payment_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME:-payment_db}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  payment_postgres_data:
