apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-app
  template:
    metadata:
      labels:
        app: payment-app
    spec:
      containers:
        - name: payment-app-container
          image: 939458930010.dkr.ecr.us-east-1.amazonaws.com/tc-fiap-payment:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: DB_HOST
              value: "tc-fiap-payment-production-postgres.ctowsmqftce2.us-east-1.rds.amazonaws.com"
            - name: DB_PORT
              value: "5432"
            - name: DB_SSLMODE
              value: "require"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB
            
            # Order Service Integration
            - name: ORDER_SERVICE_URL
              value: 'http://a99c522669cb348c2b0bfdf2e2c7b7be-57fcd899a3f33e0b.elb.us-east-1.amazonaws.com/order'
            
            # MercadoPago Configuration
            - name: MERCADO_PAGO_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: MERCADO_PAGO_BASEURL
            - name: MERCADO_PAGO_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: MERCADO_PAGO_ACCESS_TOKEN
            - name: MERCADO_PAGO_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: MERCADO_PAGO_CLIENT_ID
            - name: MERCADO_PAGO_POS_ID
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: MERCADO_PAGO_POS_ID
            - name: MERCADO_PAGO_WEBHOOK_SECRET
              valueFrom:
                secretKeyRef:
                  name: payment-secrets
                  key: MERCADO_PAGO_WEBHOOK_SECRET
            - name: MERCADO_PAGO_WEBHOOK_CALLBACK_URL
              valueFrom:
                configMapKeyRef:
                  name: payment-config
                  key: MERCADO_PAGO_WEBHOOK_CALLBACK_URL
